# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPlan',
            fields=[
                ('ActionPlanID', models.IntegerField(primary_key=True, serialize=False)),
                ('ActionPlanDescription', models.CharField(max_length=1000)),
                ('CrisisID', models.IntegerField()),
                ('CrisisDescription', models.CharField(max_length=1000)),
                ('Date_time', models.DateTimeField()),
                ('Status', models.CharField(default='ACTIVE', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CrisisOutcome',
            fields=[
                ('CrisisID', models.IntegerField(primary_key=True, serialize=False)),
                ('OutcomeDate', models.DateTimeField()),
                ('AffectedRadius', models.IntegerField()),
                ('TotalDuration', models.IntegerField()),
                ('CasualtiesCivilian', models.IntegerField()),
                ('CasualtiesEF', models.IntegerField()),
                ('CasualtiesEnemy', models.IntegerField()),
                ('DeathCivilian', models.IntegerField()),
                ('DeathEF', models.IntegerField()),
                ('DeathEnemy', models.IntegerField()),
                ('Description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='DeployForce',
            fields=[
                ('DeployForceID', models.AutoField(primary_key=True, serialize=False)),
                ('ForceType', models.CharField(max_length=200)),
                ('Utilization', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Fake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('body', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Force',
            fields=[
                ('ForceType', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('TotalTroops', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GenerateOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CallerName', models.CharField(default=10, max_length=100)),
                ('Location', models.CharField(default=0, max_length=100)),
                ('Deployment', models.CharField(default=0, max_length=100)),
                ('DeploymentAmount', models.CharField(default=0, max_length=100)),
                ('Date_time', models.CharField(default=0, max_length=100)),
                ('Description', models.CharField(default=0, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('LocationID', models.AutoField(primary_key=True, serialize=False)),
                ('Lat', models.DecimalField(decimal_places=10, max_digits=20)),
                ('Long', models.DecimalField(decimal_places=10, max_digits=20)),
                ('AOE', models.IntegerField()),
                ('Category', models.CharField(max_length=200)),
                ('ActionPlanID', models.ForeignKey(db_column='ActionPlanID', on_delete=django.db.models.deletion.CASCADE, to='app.ActionPlan')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('NotificationID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=1000)),
                ('Description', models.CharField(max_length=1000)),
                ('ToWho', models.CharField(max_length=200)),
                ('Read', models.BooleanField(default=False)),
                ('Date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OperationOrder',
            fields=[
                ('OpsID', models.AutoField(primary_key=True, serialize=False)),
                ('CrisisID', models.IntegerField()),
                ('Description', models.CharField(max_length=1000)),
                ('ActionPlanID', models.ForeignKey(db_column='ActionPlanID', on_delete=django.db.models.deletion.CASCADE, to='app.ActionPlan')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendForce',
            fields=[
                ('RecommendForceID', models.AutoField(primary_key=True, serialize=False)),
                ('ForceType', models.CharField(max_length=200)),
                ('Recommended', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Max', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ActionPlanID', models.ForeignKey(db_column='ActionPlanID', on_delete=django.db.models.deletion.CASCADE, to='app.ActionPlan')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approve', models.CharField(max_length=250)),
                ('approveDP', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('StatisticsID', models.AutoField(primary_key=True, serialize=False)),
                ('AffectedAOE', models.IntegerField()),
                ('TotalInjured', models.IntegerField()),
                ('TotalDeaths', models.IntegerField()),
                ('TotalDuration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('UpdateID', models.AutoField(primary_key=True, serialize=False)),
                ('OpsID', models.IntegerField()),
                ('Date_time', models.DateTimeField()),
                ('Type', models.CharField(max_length=1000)),
                ('Description', models.CharField(max_length=2000)),
            ],
        ),
        migrations.AddField(
            model_name='statistics',
            name='UpdateID',
            field=models.ForeignKey(db_column='UpdateID', on_delete=django.db.models.deletion.CASCADE, to='app.Update'),
        ),
        migrations.AddField(
            model_name='deployforce',
            name='OpsID',
            field=models.ForeignKey(db_column='OpsID', on_delete=django.db.models.deletion.CASCADE, to='app.OperationOrder'),
        ),
        migrations.AlterUniqueTogether(
            name='recommendforce',
            unique_together=set([('ForceType', 'ActionPlanID')]),
        ),
        migrations.AlterUniqueTogether(
            name='deployforce',
            unique_together=set([('ForceType', 'OpsID')]),
        ),
    ]
