# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171111_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployforce',
            name='Utilization',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
