# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20171111_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionplan',
            name='ActionPlanDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actionplan',
            name='CrisisDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actionplan',
            name='Status',
            field=models.TextField(blank=True, default='Active', null=True),
        ),
        migrations.AlterField(
            model_name='crisisoutcome',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='Category',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='Title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='ToWho',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operationorder',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='update',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='update',
            name='Type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
